export const albumConstants = {
    GET_PICTURES_FROM_ALBUM_REQUEST: "GET_PICTURES_FROM_ALBUM_REQUEST",
    GET_PICTURES_FROM_ALBUM_SUCCESS: "GET_PICTURES_FROM_ALBUM_SUCCESS",
    GET_PICTURES_FROM_ALBUM_FAILURE: "GET_PICTURES_FROM_ALBUM_FAILURE"
}

export const favouritesConstants = {
    ADD_TO_FAVOURITES_REQUEST: "ADD_TO_FAVOURITES_REQUEST",
    ADD_TO_FAVOURITES_SUCCESS: "ADD_TO_FAVOURITES_SUCCESS",
    ADD_TO_FAVOURITES_FAILURE: "ADD_TO_FAVOURITES_FAILURE",
    DELETE_FROM_FAVOURITES_REQUEST: "DELETE_FROM_FAVOURITES_REQUEST",
    DELETE_FROM_FAVOURITES_SUCCESS: "DELETE_FROM_FAVOURITES_SUCCESS",
    DELETE_FROM_FAVOURITES_FAILURE: "DELETE_FROM_FAVOURITES_FAILURE",
}

